nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
#    paths:
#        '^/save' :
#            allow_origin:
#                - '^http://server870015.nazwa.pl/'
#                - '^http://localhost:[0-9]+'
#                - '^http://server870015.nazwa.pl/save'
#                - '^http://listazakupow.com.pl'
#            #allow_origin: ['*']
#            allow_credentials: true
#            allow_headers: ['Authorization', 'X-Requested-With', 'content-type','Content-Type', 'Accept', 'Origin', 'X-Custom-Auth']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE','PATCH','OPTIONS']
#            max_age: 3600
#        '^/': null