home:
  path: /
  controller: App\Controller\DefaultController::index
save:
  path: /save
  controller: App\Controller\DefaultController::save
saved:
  path: /saved
  controller: App\Controller\DefaultController::saved
register:
  path: /register
  controller: App\Controller\DefaultController::register
about:
  path: /about
  controller: App\Controller\DefaultController::about
