home:
  path: /
  controller: App\Controller\DefaultController::index

savePost:
  path: /save
  controller: App\Controller\DefaultController::savePost
  methods:  [POST]

saveGet:
  path: /save
  controller: App\Controller\DefaultController::saveGet
  methods:  [GET]

saved:
  path: /saved
  controller: App\Controller\DefaultController::saved