home:
  path: /
  controller: App\Controller\DefaultController::index

savePost:
  path: /save
  controller: App\Controller\DefaultController::savePost
  methods:  [POST]

saveGet:
  path: /save
  controller: App\Controller\DefaultController::saveGet
  methods:  [GET, HEAD, PUT, DELETE, CONNECT, TRACE, PATCH, VIEW, UNLINK, PURGE, LOCK, UNLOCK, LINK, PROPFIND]

saved:
  path: /saved
  controller: App\Controller\DefaultController::saved